export const technologyOptions = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C#",
  "Go",
  "Rust",
  "C++",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "React",
  "Vue",
  "Angular",
  "Next.js",
  "Nuxt",
  "Node.js",
  "Express",
  "Hono",
  "Django",
  "Flask",
  "FastAPI",
  ".NET",
  "Spring Boot",
  "Laravel",
  "Tailwind CSS",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "MongoDB",
  "Redis",
  "GraphQL",
  "REST APIs",
  "Docker",
  "Kubernetes",
  "Terraform",
  "AWS",
  "Azure",
  "Google Cloud",
  "Cloudflare",
  "GitHub Actions",
  "CI/CD",
  "Linux",
  "React Native",
  "Flutter",
  "Figma",
  "Playwright",
  "Jest",
  "Pandas"
] as const;

export const skillOptions = [
  "Communication",
  "Leadership",
  "Problem Solving",
  "Critical Thinking",
  "Collaboration",
  "Teamwork",
  "Project Management",
  "Product Thinking",
  "Customer Empathy",
  "Analytical Thinking",
  "Adaptability",
  "Time Management",
  "Stakeholder Management",
  "Presentation Skills",
  "Technical Writing",
  "Mentoring",
  "Coaching",
  "Research",
  "Strategy",
  "Planning",
  "Execution",
  "Decision Making",
  "Attention to Detail",
  "Quality Assurance",
  "Testing",
  "Debugging",
  "System Design",
  "Architecture",
  "API Design",
  "Data Analysis",
  "Data Visualization",
  "Machine Learning",
  "Automation",
  "Scripting",
  "DevOps",
  "Security Awareness",
  "Accessibility",
  "UX Thinking",
  "Design Systems",
  "Agile",
  "Scrum",
  "Cross-functional Leadership",
  "Conflict Resolution",
  "Negotiation",
  "Requirements Gathering",
  "Documentation",
  "Public Speaking",
  "Interviewing",
  "Prioritization",
  "Continuous Improvement"
] as const;
